 services:
  web:
    build: .
    #command: python /code/aquinus/manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    command: ["uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
              
    restart: always
    volumes:
      - .:/code
   
    environment:
      - DJANGO_SETTINGS_MODULE=aquinus.settings.prod
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"