# Generated by Django 5.1.1 on 2024-09-07 22:39

import apps.cursos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=False)),
                ('puede_calificar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('ANUAL', 'A'), ('SEMESTRAL', 'S'), ('CUATRIMESTRAL', 'C'), ('TRIMESTRAL', 'T')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cursante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_alumno', to='alumnos.persona')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alumno_curso', to='cursos.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tipo', models.CharField(choices=[('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('PROMEDIO CURSADA', 'Promedio Cursada'), ('EXAMEN FINAL', 'Examen Final'), ('FINAL', 'Final'), ('COMPLEMENTARIO', 'Complementario'), ('ORDINARIA', 'Ordinaria')], max_length=50)),
                ('numero_complementario', models.IntegerField(blank=True, null=True)),
                ('cursante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nota_cursante', to='cursos.cursante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calificacion_materia', to='cursos.materia')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=10)),
                ('anio', models.IntegerField(help_text='Ingrese el año del plan de estudio.', validators=[apps.cursos.models.validate_four_digits])),
                ('vigente', models.BooleanField(default=True)),
                ('materias', models.ManyToManyField(related_name='materias_plan_de_estudio', to='cursos.materia')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='plan_de_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plan_estudio_curso', to='cursos.planestudio'),
        ),
    ]
