# Generated by Django 5.1.1 on 2024-09-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planestudio',
            name='unique_especialidad_anio',
        ),
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(fields=('especialidad', 'orientacion', 'anio'), name='unique_especialidad_anio'),
        ),
    ]
