# Generated by Django 5.1.1 on 2024-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_calificaciones_calificador_calificaciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='tipo',
            field=models.CharField(choices=[('ANUAL', 'ANUAL'), ('SEMESTRAL', 'SEMESTRAL'), ('CUATRIMESTRAL', 'CUATRIMESTRAL'), ('TRIMESTRAL', 'TRIMESTRAL')], max_length=50),
        ),
    ]
