# Generated by Django 5.1.1 on 2024-09-14 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_planestudio_unique_especialidad_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursante',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_curso', to='cursos.curso'),
        ),
    ]
