# Generated by Django 5.1.1 on 2024-09-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_materia_tipo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(fields=('especialidad', 'anio'), name='unique_especialidad_anio'),
        ),
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('especialidad',), name='unique_especialidad_vigente'),
        ),
    ]
