# Generated by Django 5.1.1 on 2024-09-09 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_planestudio_unique_especialidad_anio_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planestudio',
            name='unique_especialidad_vigente',
        ),
    ]
