# Generated by Django 5.1.1 on 2024-09-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_created_at_curso_updated_at_curso_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
