# Generated by Django 5.1.1 on 2024-09-09 15:17

import apps.cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_planestudio_unique_especialidad_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='anio',
            field=models.IntegerField(validators=[apps.cursos.models.validate_four_digits]),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='materias',
            field=models.ManyToManyField(help_text='Materias asociadas al plan de estudio', related_name='materias_plan_de_estudio', to='cursos.materia'),
        ),
    ]
