# Generated by Django 5.1.1 on 2024-09-16 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_cursante_activo'),
        ('usuarios', '0005_perfil_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ManyToManyField(related_name='profesor_curso', to='cursos.curso')),
                ('materias', models.ManyToManyField(related_name='profesor_materia', to='cursos.materia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='calificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.profesor'),
        ),
    ]
