# Generated by Django 5.1.1 on 2024-09-10 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_materia_observaciones_alter_planestudio_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='fecha_examen',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
