# Generated by Django 5.1.1 on 2024-09-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_profesor_alter_calificaciones_calificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
