# Generated by Django 5.1.1 on 2024-09-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_calificaciones_fecha_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='division',
            field=models.IntegerField(default=1),
        ),
    ]
