# Generated by Django 5.1.1 on 2024-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
