# Generated by Django 5.1.1 on 2024-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='planestudio',
            name='orientacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
