# Generated by Django 5.1.1 on 2024-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_planestudio_orientacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planestudio',
            name='especialidad',
            field=models.CharField(choices=[('IN', 'IN'), ('EL', 'EL'), ('AE', 'AE'), ('MW', 'MW'), ('AN', 'AN'), ('IM', 'IM'), ('MA', 'MA'), ('AG', 'AG'), ('MQ', 'MQ'), ('EN', 'EN'), ('FU', 'FU'), ('OP', 'OP'), ('CO', 'CO'), ('SH', 'SH'), ('MU', 'MU')], max_length=10),
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='orientacion',
            field=models.CharField(blank=True, choices=[('ME', 'ME'), ('MS', 'MS'), ('HI', 'HI'), ('AM', 'AM'), ('AV', 'AV'), ('MC', 'MC'), ('OPCR/AC', 'OPCR/AC'), ('OPDT', 'OPDT'), ('SU', 'SU'), ('EMMH', 'EMMH'), ('AE', 'AE'), ('AEAM', 'AEAM'), ('AEAV', 'AEAV'), ('AEMC', 'AEMC'), ('AESU', 'AESU'), ('CO', 'CO'), ('EL', 'EL'), ('OC', 'OC'), ('FU', 'FU'), ('IN', 'IN'), ('CA', 'CA'), ('MO', 'MO'), ('SC', 'SC'), ('TB', 'TB'), ('MU', 'MU'), ('AA', 'AA'), ('GN', 'GN'), ('EN', 'EN'), ('BA', 'BA'), ('AC', 'AC'), ('EE', 'EE'), ('II', 'II'), ('MT', 'MT'), ('AU', 'AU'), ('EM', 'EM'), ('CC', 'CC'), ('CD', 'CD'), ('CM', 'CM'), ('PE', 'PE'), ('IM', 'IM'), ('(ITD)', '(ITD)'), ('MA', 'MA'), ('MQ', 'MQ'), ('AS', 'AS'), ('CP', 'CP'), ('CT', 'CT'), ('MN', 'MN'), ('SO', 'SO'), ('RC', 'RC'), ('EESI', 'EESI'), ('EECT', 'EECT'), ('EMAM', 'EMAM'), ('EMEL', 'EMEL'), ('RD', 'RD'), ('SR', 'SR'), ('EMPR', 'EMPR')], max_length=10, null=True),
        ),
    ]
