# Generated by Django 5.1.1 on 2024-09-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_curso_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(choices=[(1, '1er año'), (2, '2do año'), (3, '3er año'), (4, '4to año'), (5, '5to año')]),
        ),
    ]
