# Generated by Django 5.1.1 on 2024-09-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_planestudio_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='area',
            field=models.CharField(default='sin area', max_length=50),
            preserve_default=False,
        ),
    ]
