# Generated by Django 5.1.1 on 2024-09-20 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_curso_anio'),
        ('usuarios', '0006_perfil_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
