# Generated by Django 5.1.1 on 2024-09-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_materia_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='regimen',
            field=models.CharField(choices=[('PROMOCIONABLE', 'PROMOCIONABLE'), ('NO PROMOCIONABLE', 'NO PROMOCIONABLE'), ('ESPECIAL', 'ESPECIAL')], default='NO PROMOCIONABLE', max_length=50),
            preserve_default=False,
        ),
    ]
