# Generated by Django 5.1.1 on 2024-09-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_materia_regimen'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='anio',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planestudio',
            name='especialidad',
            field=models.CharField(choices=[('AE', 'AE'), ('AG', 'AG'), ('AN', 'AN'), ('CO', 'CO'), ('EL', 'EL'), ('EN', 'EN'), ('FU', 'FU'), ('IM', 'IM'), ('IN', 'IN'), ('IPDSV', 'IPDSV'), ('MA', 'MA'), ('MQ', 'MQ'), ('MU', 'MU'), ('MW', 'MW'), ('OP', 'OP'), ('SH', 'SH')], max_length=10),
        ),
    ]
