# Generated by Django 5.1.1 on 2024-09-23 11:59

import apps.cursos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_alter_profesor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasExamenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.IntegerField(validators=[apps.cursos.models.validate_four_digits])),
                ('regimen_materia', models.CharField(choices=[('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('PROMEDIO CURSADA', 'Promedio Cursada'), ('EXAMEN FINAL', 'Examen Final'), ('FINAL', 'Final'), ('COMPLEMENTARIO', 'Complementario'), ('ORDINARIA', 'Ordinaria')], max_length=50)),
                ('subPeriodo', models.CharField(max_length=100)),
                ('fechaInicioCalificacion', models.DateField()),
                ('fechaTopeCalificacion', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
