# Generated by Django 5.1.1 on 2024-09-23 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_alter_fechasexamenes_regimen_materia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fechasexamenes',
            constraint=models.UniqueConstraint(fields=('anio_lectivo', 'regimen_materia', 'subPeriodo'), name='combinacion_unica'),
        ),
    ]
