# Generated by Django 5.1.1 on 2024-09-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_fechasexamenes_combinacion_unica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechasexamenes',
            name='fechaTopeCalificacion',
            field=models.DateField(),
        ),
    ]
