# Generated by Django 5.1.1 on 2024-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_alter_fechasexamenes_fechatopecalificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechasexamenes',
            name='aplica_para',
            field=models.CharField(choices=[('TODOS', 'TODOS LOS AÑOS'), ('1', 'PRIMER AÑO'), ('2', 'SEGUNDO AÑO'), ('3', 'TERCER AÑO')], default='TODOS', max_length=50),
        ),
    ]
