# Generated by Django 5.1.1 on 2024-09-27 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_fechasexamenes_aplica_para'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fechasexamenes',
            name='combinacion_unica',
        ),
        migrations.AddConstraint(
            model_name='fechasexamenes',
            constraint=models.UniqueConstraint(fields=('anio_lectivo', 'regimen_materia', 'subPeriodo', 'aplica_para'), name='combinacion_unica'),
        ),
    ]
