# Generated by Django 5.1.1 on 2024-09-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_materia_regimen_especial_alter_materia_regimen'),
        ('usuarios', '0006_perfil_tratamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='materia',
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_cursado', models.IntegerField(blank=True, choices=[], null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='cursos.curso')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.materia')),
                ('profesor', models.ManyToManyField(blank=True, related_name='profesores_de_asignaturas', to='usuarios.perfil')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='asignatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calificacion_materia', to='cursos.asignatura'),
            preserve_default=False,
        ),
    ]
