# Generated by Django 5.1.1 on 2024-09-30 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_remove_calificaciones_materia_asignatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='materias',
        ),
    ]
