# Generated by Django 5.1.1 on 2024-10-02 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_remove_profesor_curso_remove_profesor_materias'),
        ('usuarios', '0007_alter_perfil_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='calificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='periodo_cursado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
