# Generated by Django 5.1.1 on 2024-10-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_alter_calificaciones_calificador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='calificaciones',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
