# Generated by Django 5.1.1 on 2024-11-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0023_alter_materia_options_alter_calificaciones_valor'),
        ('usuarios', '0009_alter_perfil_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='tipo',
            field=models.CharField(choices=[('BIMESTRAL_1', 'Primer Bimestre'), ('BIMESTRAL_2', 'Segundo Bimestre'), ('TRIMESTRAL_1', 'Primer Trimestre'), ('TRIMESTRAL_2', 'Segundo Trimestre'), ('TRIMESTRAL_3', 'Tercer Trimestre'), ('PROMEDIO CURSADA', 'Promedio Cursada'), ('EXAMEN FINAL', 'Examen Final'), ('FINAL', 'Final'), ('COMPLEMENTARIO', 'Complementario'), ('ORDINARIA', 'Ordinaria')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='calificaciones',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'ORDINARIA'), _negated=True), fields=('asignatura', 'cursante', 'tipo'), name='unique_calificacion_per_tipo'),
        ),
    ]
