# Generated by Django 5.1.1 on 2024-12-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0024_alter_calificaciones_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calificaciones',
            name='unique_calificacion_per_tipo',
        ),
    ]
