"""
Django settings for aquinus project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_2+-4k8af_(^&hwzql+07zwjvy1jwn47jn6=%87)#op*@-1cyc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_select2',
    'apps.alumnos',
    'apps.usuarios',
    'apps.main',
    'apps.cursos', 
    'apps.utils',
    'apps.calificaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'apps.usuarios.middleware.VerificarCambioContrasenaMiddleware',
            'aquinus.custom_middleware.CurrentUserMiddleware',


]

ROOT_URLCONF = 'aquinus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ], # Ruta a tu carpeta de plantillas],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aquinus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

"""
Configuración para trabajar en ESSA con servidor en linea

"""
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "aquinus",
#         "USER": "ezangara",
#         "PASSWORD": "Armada2024@",
#         "HOST": "192.16.0.252",  # O la dirección IP de tu servidor MySQL
#         "PORT": "3306",  # El puerto de tu servidor MySQL},
#     },
#     "id8": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": "aspi",
#         "USER": "ezangara",
#         "PASSWORD": "Armada2024@",
#         "HOST": "192.16.0.252",  # O la dirección IP de tu servidor MySQL
#         "PORT": "3306",  # El puerto de tu servidor MySQL},
#     },
# }
"""
Configuración para trabajar OFFLINE
"""
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "aquinus",
        "USER": "ezangara",
        "PASSWORD": "Armada2024@",
        "HOST": "localhost",  # O la dirección IP de tu servidor MySQL
        "PORT": "3306",  # El puerto de tu servidor MySQL},
    },
    "id8": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "aspi",
        "USER": "ezangara",
        "PASSWORD": "Armada2024@",
        "HOST": "localhost",  # O la dirección IP de tu servidor MySQL
        "PORT": "3306",  # El puerto de tu servidor MySQL},
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTHENTICATION_BACKENDS = [
    'apps.usuarios.custom_auth_backend.DNIAuthBackend',
    'django.contrib.auth.backends.ModelBackend',  # Mantén el backend predeterminado como respaldo
]
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-la'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# URL para acceder a archivos estáticos
STATIC_URL = '/static/'

# Directorio donde se recolectan los archivos estáticos para producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Aquí puedes colocar archivos estáticos globales para tu proyecto
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_URL = 'usuarios:login'  # URL para la página de login
LOGIN_REDIRECT_URL = '/'  # URL a la que se redirige después del login exitoso
LOGOUT_REDIRECT_URL = 'usuarios:login'  # URL a la que se redirige después del logout

MESSAGE_TAGS = {
    message_constants.DEBUG: 'alert-secondary',  # Puedes usar 'alert-secondary' para debug
    message_constants.INFO: 'alert-info',        # Para mensajes de info
    message_constants.SUCCESS: 'alert-success',  # Para mensajes de éxito
    message_constants.WARNING: 'alert-warning',  # Para advertencias
    message_constants.ERROR: 'alert-danger',     # Para errores
}


SELECT2_JS = ['assets/select2/js/select2.min.js']
SELECT2_CSS = [
    'assets/select2/css/select2.css',
    'assets/select2/bootstrap5-theme/select2-bootstrap-5-theme.min.css'
    
]