# Generated by Django 5.1.1 on 2024-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('grado', models.CharField(default=None, max_length=45, null=True)),
                ('apellidos', models.CharField(max_length=45)),
                ('nombres', models.CharField(max_length=45)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('mr', models.CharField(max_length=8, unique=True)),
                ('batallon', models.CharField(default=None, max_length=45, null=True)),
                ('compania', models.CharField(default=None, max_length=45, null=True)),
                ('division', models.CharField(default=None, max_length=45, null=True)),
                ('sexo', models.CharField(default=None, max_length=45, null=True)),
                ('promocion', models.IntegerField(default=None, null=True)),
                ('especialidad', models.CharField(default=None, max_length=45, null=True)),
                ('orientacion', models.CharField(default=None, max_length=45, null=True)),
                ('estado', models.CharField(default=None, max_length=45, null=True)),
            ],
            options={
                'db_table': 'vista_orione',
                'managed': False,
            },
        ),
    ]
