# Generated by Django 5.1.1 on 2024-09-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_es_staff_perfil_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
