# Generated by Django 5.1.1 on 2024-09-06 21:59

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_perfil_activo_remove_perfil_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='debe_cambiar_contraseña',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.PositiveIntegerField(unique=True, validators=[apps.usuarios.models.validar_digitos], verbose_name='DNI'),
        ),
    ]
