# Generated by Django 5.1.1 on 2024-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_debe_cambiar_contraseña_alter_perfil_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='area',
            field=models.CharField(choices=[('GESTION', 'GESTION'), ('DOCENTE', 'DOCENTE'), ('CUERPO', 'CUERPO'), ('ADMINISTRADOR', 'ADMINISTRADOR')], default='GESTION', max_length=100),
            preserve_default=False,
        ),
    ]
