# Generated by Django 5.1.1 on 2024-09-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tratamiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
