# Generated by Django 5.1.1 on 2024-10-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfil_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CUERPO', 'CUERPO'), ('DOCENTE', 'DOCENTE'), ('CAL_Y_EST', 'CALIFICACIONES Y ESTADÍSTICA'), ('CURSOS', 'CURSOS')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PROFESOR', 'PROFESOR'), ('ADMINISTRADOR', 'ADMINISTRADOR'), ('CONSUMIDOR', 'CONSUMIDOR'), ('STAFF', 'STAFF')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='area',
        ),
        migrations.AddField(
            model_name='perfil',
            name='areas',
            field=models.ManyToManyField(to='usuarios.area'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='roles',
            field=models.ManyToManyField(to='usuarios.rol'),
        ),
    ]
