# Generated by Django 5.1.1 on 2024-10-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_perfil_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tratamiento',
            field=models.CharField(blank=True, default='Sr/a.', max_length=50, null=True),
        ),
    ]
