# Generated by Django 5.1.1 on 2024-10-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_tratamiento'),
        ('usuarios', '0007_area_rol_remove_perfil_area_perfil_areas_and_more'),
    ]

    operations = [
    ]
