# Generated by Django 5.1.1 on 2024-10-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_merge_20241003_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tratamiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
